<?php

namespace App\Form;



use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options) :void
    {
//        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
//        $builder
//            ->add('avatarFile', VichImageType::class, [
//                'required' => false,
////                'allow_delete' => true, // Allow the deletion of images
////                'download_label' => '...',
//                'label' => 'Avatar Image',
////                'download_uri' => true,
////                'image_uri' => true
//            ])
//            // Add other fields as needed
//            ->add('fullName')
//            ->add('birthday');
        $builder
            ->add('avatarFile', VichImageType::class, [
                'required' => false,
                'label' => 'Avatar Image',
            ])
            ->add('fullName')
            ->add('birthday');
    }
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            'csrf_protection' => false
        ]);
    }
}