nelmio_api_doc:
  documentation:
    info:
      title: SmartFin
      description: Your ultimate financial dashboard with intuitive tools for smart financial management
      version: 1.0.0
    tags:
      - name: "Budgets"
        description: "These are all of the endpoints that have to do with budgets"
      - name: "Overview"
        description: "API endpoints used for overview page"
      - name: "Categories"
        description: "These are all of the endpoints that have to do with categories"
      - name: "Transactions"
        description: "These are all of the endpoints that have to do with transactions"
      - name: "Transaction Templates"
        description: "These are all of the endpoints that have to do with transaction templates"
      - name: "Entry Points"
        description: "These are the main entry points for out site"
      - name: "User"
        description: "These are all of the endpoints that have to do with user"
      - name: "Exports"
        description: "Everything that has to do with exporting or viewing the exported files"
      - name: "Mailer"
        description: "Mailer service used for sending emails"
      - name: "Generators"
        description: "PDF and XLS file generators"
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT

      schemas:
        QuerySuccessResponse:
          type: object
          properties:
            success:
              type: boolean
            data:
              type: object
              properties:
                pagination:
                  type: object
                  properties:
                    currentPage:
                      type: string
                      example: '1'
                    previousPage:
                      type: integer
                      example: null
                    nextPage:
                      type: integer
                      example: null
                    totalPages:
                      type: integer
                      example: 1
        Budget:
          allOf:
            - $ref: '#/components/schemas/QuerySuccessResponse'
            - type: object
              properties:
                data:
                  properties:
                    budgets:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 2
                          monthlyBudget:
                            type: number
                            example: 1758.14
                          monthlyBudgetDate:
                            type: string
                            format: date-time
                            example: "2024-07-23T00:00:00+00:00"
                          categoryID:
                            type: integer
                            example: 9
                          categoryName:
                            type: string
                            example: "Nights out"
                          color:
                            type: string
                            example: "#607D8B"
                          total:
                            type: number
                            example: 5876.911
                          percent:
                            type: number
                            example: 334.2686589236352
        FailedAction:
          type: object
          properties:
            success:
              type: boolean
              example: false
        SuccessfulAction:
          type: object
          properties:
            success:
              type: boolean
              example: true
        BudgetNotFound:
          allOf:
            - $ref: '#/components/schemas/FailedAction'
            - type: object
              properties:
                message:
                  example: "Budget not found"
        BudgetsNotFound:
          allOf:
            - $ref: '#/components/schemas/FailedAction'
            - type: object
              properties:
                message:
                  example: "Budgets not found"
        InputError:
          type: object
          properties:
            success:
              type: boolean
              example: false
        BudgetDateError:
          allOf:
            - $ref: '#/components/schemas/InputError'
            - type: object
              properties:
                errors:
                  type: array
                  items:
                    properties:
                      field:
                        example: "dateStart"
                      message:
                        example: "Given date must be in format YYYY-MM-DD"
                      code:
                        example: "69819696-02ac-4a99-9ff0-14e127c4d1bc"
        YearInputError:
          allOf:
            - $ref: '#/components/schemas/InputError'
            - type: object
              properties:
                errors:
                  type: array
                  items:
                    properties:
                      field:
                        example: "year"
                      message:
                        example: "'da' is not an integer."
                      code:
                        example: "integer_type"
        BudgetInputError:
          allOf:
            - $ref: '#/components/schemas/InputError'
            - type: object
              properties:
                errors:
                  type: array
                  items:
                    properties:
                      field:
                        type: string
                        example: "categoryId"
                      message:
                        type: string
                        example: "0 is not a positive number"
                      code:
                        type: string
                        format: string
                        example: "positive_number"
        BudgetInputSuccess:
          allOf:
            - $ref: '#/components/schemas/SuccessfulAction'
            - type: object
              properties:
                message:
                  example: "New budget created"
        BudgetInputFail:
          allOf:
            - $ref: '#/components/schemas/FailedAction'
            - type: object
              properties:
                message:
                  example: "Invalid category given"
        BudgetConflict:
          allOf:
            - $ref: '#/components/schemas/FailedAction'
            - type: object
              properties:
                message:
                  example: "'You already have a budget for this category in given month"
        BudgetUpdateSuccess:
          allOf:
            - $ref: '#/components/schemas/SuccessfulAction'
            - type: object
              properties:
                message:
                  example: "Update successful"
        BudgetUpdateFail:
          allOf:
            - $ref: '#/components/schemas/FailedAction'
            - type: object
              properties:
                message:
                  example: "Category could not be found"
        BudgetDeleteSuccess:
          allOf:
            - $ref: '#/components/schemas/SuccessfulAction'
            - type: object
              properties:
                message:
                  example: "Budget with id 1 has been deleted"
        BudgetDeleteFail:
          allOf:
            - $ref: '#/components/schemas/FailedAction'
            - type: object
              properties:
                message:
                  example: "Budget not found or not owned by you"
        BudgetRandomResult:
          allOf:
            - $ref: '#/components/schemas/SuccessfulAction'
            - type: object
              properties:
                data:
                  type: array
                  items:
                    properties:
                      id:
                        example: 33
                      monthlyBudget:
                        example: 2607.71
                      monthlyBudgetDate:
                        example: "2024-07-31T00:00:00+00:00"
                      categoryId:
                        example: 12
                      categoryName:
                        example: "Other"
                      color:
                        example: "#FF9800"
                      totalSpent:
                        example: 7868.837
                      percentageSpent:
                        example: 301.75276391930083
        Category:
          allOf:
            - $ref: '#/components/schemas/QuerySuccessResponse'
            - type: object
              properties:
                data:
                  properties:
                    categories:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 3
                          categoryName:
                            type: string
                            example: "Gift"
                          type:
                            type: string
                            enum: [ "income" ]
                            example: "income"
                          color:
                            type: string
                            example: "#2196F3"
        CategoryNotFound:
          allOf:
            - $ref: '#/components/schemas/FailedAction'
            - type: object
              properties:
                message:
                  example: "No categories found"
        CategoryQueryError:
          allOf:
            - $ref: '#/components/schemas/InputError'
            - type: object
              properties:
                errors:
                  type: array
                  items:
                    properties:
                      field:
                        example: "page"
                      message:
                        example: "'123d' is not an integer."
                      code:
                        example: "integer_type"
        CategoryInputError:
          allOf:
            - $ref: '#/components/schemas/InputError'
            - type: object
              properties:
                errors:
                  type: array
                  items:
                    type: object
                    properties:
                      field:
                        example: "categoryName"
                      message:
                        example: "Category name must be provided and cannot be blank"
                      code:
                        example: "c1051bb4-d103-4f74-8988-acbcafc7fdc3"

        CategoryInputSuccess:
          type: object
          properties:
            success:
              type: boolean
              example: true
            message:
              type: string
              example: "New category created"
        CategoryUpdateSuccess:
          allOf:
            - $ref: '#/components/schemas/SuccessfulAction'
            - type: object
              properties:
                message:
                  example: "Update successful"
        CategoryForbidden:
          allOf:
            - $ref: '#/components/schemas/FailedAction'
          type: object
          properties:
            message:
              example: "You cannot modify default category."
        CategoryDeleteSuccess:
          allOf:
            - $ref: '#/components/schemas/FailedAction'
            - type: object
              properties:
                message:
                  example: "Category deleted with id=1"
        CategoryForbiddenDelete:
          allOf:
            - $ref: '#/components/schemas/FailedAction'
          type: object
          properties:
            message:
              example: "You cannot delete default category."
        CategoryFailed:
          allOf:
            - $ref: '#/components/schemas/FailedAction'
            - type: object
              properties:
                message:
                  example: "Category not found or does not belong to the user."
        Unauthorized:
          type: object
          properties:
            code:
              type: integer
              example: 401
            message:
              type: string
              example: "JWT Token not found"
        InvalidRequest:
          allOf:
            - $ref: '#/components/schemas/FailedAction'
            - type: object
              properties:
                message:
                  type: string
                  example: "Request payload contains invalid \"json\" data."
    security:
      - Bearer: [ ]
  areas: # to filter documented areas
    default:
      path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
        - ^/api(?!/doc$)