nelmio_api_doc:
    documentation:
        info:
            title: SmartFin
            description: Your ultimate financial dashboard with intuitive tools for smart financial management
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas: # to filter documented areas
        default:
            path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
                - ^/api(?!/doc$)