symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 300 # 5 minutes
    throttle_limit: 600  # 10-minute cooldown
    enable_garbage_collection: true